// Code generated by "stringer -type flag -linecomment"; DO NOT EDIT.

package cmd

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[And-0]
	_ = x[Blv-1]
	_ = x[Dir-2]
	_ = x[Facets-3]
	_ = x[Index-4]
	_ = x[JSON-5]
	_ = x[Or-6]
	_ = x[Params-7]
	_ = x[Query-8]
	_ = x[Refine-9]
	_ = x[Search-10]
	_ = x[Workers-11]
	_ = x[UI-12]
}

const _flag_name = "andbrowsedirfacetindexjsonorparamsqueryrefinesearchworkersui"

var _flag_index = [...]uint8{0, 3, 9, 12, 17, 22, 26, 28, 34, 39, 45, 51, 58, 60}

func (i flag) String() string {
	if i < 0 || i >= flag(len(_flag_index)-1) {
		return "flag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _flag_name[_flag_index[i]:_flag_index[i+1]]
}
