// Code generated by "stringer -type flag -linecomment"; DO NOT EDIT.

package cmd

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[B-0]
	_ = x[D-1]
	_ = x[F-2]
	_ = x[I-3]
	_ = x[J-4]
	_ = x[P-5]
	_ = x[Q-6]
	_ = x[R-7]
	_ = x[S-8]
	_ = x[T-9]
	_ = x[W-10]
	_ = x[U-11]
}

const _flag_name = "browsedirfacetindexjsonparamsqueryrefinesearchtextworkersui"

var _flag_index = [...]uint8{0, 6, 9, 14, 19, 23, 29, 34, 40, 46, 50, 57, 59}

func (i flag) String() string {
	if i < 0 || i >= flag(len(_flag_index)-1) {
		return "flag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _flag_name[_flag_index[i]:_flag_index[i+1]]
}
